### ISSUE TITLE
Cloud issue?

### ISSUE THREAD

**Issue by prysmakou** [cloudfoundry-incubator/diego-windows-release#1]
Tried to deploy it with Cloud Formation. During investigating found the reason -  lack of internet connection for windows box. I specified id of my NAT VM (based on amazon's NAT AMI) and CIDR for new subnet. 
What do you mean for NATZ? A NAT instance?
 Looks like it is needed to modify NAT instance somehow before deployment of Windows cell?

I already have CF and Diego deployed, so I have public and private subnet and NAT instance. 
Why we need to create additional subnet for Windows cells instead of using existing (private) subnet?

cfn-init.log contains:
```
2015-10-11 10:40:40,540 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2015-10-11 10:40:40,540 [DEBUG] Describing resource GardenWindowsInstanceConfiguration in stack arn:aws:cloudformation:us-east-1:754058048930:stack/win2/da263ce0-7003-11e5-b978-50e2416294a8
2015-10-11 10:41:01,618 [ERROR] ConnectionError
Traceback (most recent call last):
  File "cfnbootstrap\util.pyc", line 159, in _retry
  File "cfnbootstrap\util.pyc", line 231, in _timeout
ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```

**Comment by prysmakou** [comment]
After small modification of the template (I just specified my CF/Diego's subnet) debug-stderr contains:
```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
main.main()
	C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:138 +0x1f5e

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08208c0b0)
	c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08208c0b0)
	c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:661 +0xcc3
'C:\tmp\dwminst\install.bat' is not recognized as an internal or external command,
operable program or batch file.
```
And this is true, there is no `C:\tmp\dwminst\install.bat`.
